"""Course model changed

Revision ID: 6768ba937bb7
Revises: d82364cc4f14
Create Date: 2024-10-23 16:56:32.751072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6768ba937bb7'
down_revision = 'd82364cc4f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
