"""Course Database changed

Revision ID: 990201c50a7f
Revises: 6768ba937bb7
Create Date: 2024-10-23 17:16:30.596569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990201c50a7f'
down_revision = '6768ba937bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
